# Site settings
baseurl = "https://rogiersbart.github.io/espresso/"
languageCode = "en-uk"
title = "espresso"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    # Meta
    title = "[espresso](https://rogiersbart.github.io/espresso)"
    subtitle = "[rogiersbart.github.io](https://rogiersbart.github.io)"
    author = "Bart Rogiers [rogiersbart]"
    description = ""
    keywords = ""

    # Body background color
    bodybgcolor = "#ffffff"

    # Preview container button text
    buttontext = "Download source"

    # Footer text
    footertext = ""

    # add extra-css
    # custom_css = ["css/extra1.css", "css/extra2.css"]
