# Site settings
baseurl = "https://rogiersbart.github.io/espresso/"
languageCode = "en-us"
title = "espresso"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    # Meta
    title = "[espresso](https://rogiersbart.github.io/espresso)"
    subtitle = "[rogiersbart.github.io](https://rogiersbart.github.io)"
    author = "Bart Rogiers [rogiersbart]"
    description = "Hugrid - grid theme for Hugo with an expanding image preview."
    keywords = "Hugo, Hugo theme, grid theme, portfolio, bookmarks, collection, contacts"

    # Body background color
    bodybgcolor = "#ffffff"

    # Preview container button text
    buttontext = "Full resolution"

    # Footer text
    footertext = ""

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
